# Generated by Django 5.0.3 on 2024-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("DataHandler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugTuple",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("product", models.CharField(max_length=50, verbose_name="product")),
                (
                    "component",
                    models.CharField(max_length=50, verbose_name="component"),
                ),
                ("assignee", models.CharField(max_length=50, verbose_name="assignee")),
                ("status", models.CharField(max_length=10, verbose_name="status")),
                ("summary", models.CharField(max_length=300, verbose_name="summary")),
                ("version", models.CharField(max_length=10, verbose_name="version")),
                ("platform", models.CharField(max_length=50, verbose_name="platform")),
                ("op_sys", models.CharField(max_length=50, verbose_name="op_sys")),
                ("priority", models.CharField(max_length=10, verbose_name="priority")),
                ("severity", models.CharField(max_length=10, verbose_name="severity")),
                ("QA", models.CharField(max_length=50, verbose_name="QA")),
                ("ccList", models.CharField(max_length=200, verbose_name="ccList")),
                ("reportedId", models.IntegerField(verbose_name="id")),
            ],
            options={
                "verbose_name": "BugTuple",
                "verbose_name_plural": "BugTuples",
                "db_table": "bug_tuple",
                "ordering": ["-reportedId"],
                "permissions": (
                    ("my_view_bugtuple", "查看BugTuple"),
                    ("my_add_bugtuple", "添加BugTuple"),
                ),
                "get_latest_by": "reported",
            },
        ),
    ]
