# Generated by Django 5.0.3 on 2024-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("DataHandler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugTuple",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("alias", models.CharField(max_length=50, verbose_name="alias")),
                ("summary", models.CharField(max_length=300, verbose_name="summary")),
                ("status", models.CharField(max_length=10, verbose_name="status")),
                ("product", models.CharField(max_length=50, verbose_name="product")),
                (
                    "component",
                    models.CharField(max_length=50, verbose_name="component"),
                ),
                ("version", models.CharField(max_length=10, verbose_name="version")),
                ("hardware", models.CharField(max_length=50, verbose_name="hardware")),
                (
                    "importance",
                    models.CharField(max_length=10, verbose_name="importance"),
                ),
                ("QA", models.CharField(max_length=50, verbose_name="QA")),
                ("keywords", models.CharField(max_length=200, verbose_name="keywords")),
                ("reported", models.DateTimeField(verbose_name="reported")),
                ("modified", models.DateTimeField(verbose_name="modified")),
                ("ccList", models.CharField(max_length=200, verbose_name="ccList")),
                ("assignee", models.CharField(max_length=50, verbose_name="assignee")),
            ],
            options={
                "verbose_name": "BugTuple",
                "verbose_name_plural": "BugTuples",
                "db_table": "bug_tuple",
                "ordering": ["-reported"],
                "permissions": (
                    ("my_view_bugtuple", "查看BugTuple"),
                    ("my_add_bugtuple", "添加BugTuple"),
                ),
                "get_latest_by": "reported",
                "indexes": [
                    models.Index(
                        fields=["alias", "summary"], name="bug_tuple_alias_832c18_idx"
                    )
                ],
                "unique_together": {("alias", "summary")},
            },
        ),
    ]
