# Generated by Django 5.0.3 on 2024-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataHandler", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugtuple",
            name="version",
            field=models.CharField(max_length=30, verbose_name="version"),
        ),
    ]
