# Generated by Django 5.0.3 on 2024-04-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DataHandler", "0003_alter_bugtuple_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugtuple",
            name="priority",
            field=models.CharField(max_length=30, verbose_name="priority"),
        ),
        migrations.AlterField(
            model_name="bugtuple",
            name="severity",
            field=models.CharField(max_length=30, verbose_name="severity"),
        ),
        migrations.AlterField(
            model_name="bugtuple",
            name="status",
            field=models.CharField(max_length=30, verbose_name="status"),
        ),
    ]
