# Generated by Django 5.0.3 on 2024-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DataHandler",
            "0004_alter_bugtuple_priority_alter_bugtuple_severity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugtuple",
            name="ccList",
            field=models.CharField(max_length=600, verbose_name="ccList"),
        ),
    ]
