# Generated by Django 5.0.3 on 2024-04-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("DataHandler", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "commentator",
                    models.CharField(max_length=50, verbose_name="commentator"),
                ),
                ("content", models.TextField(max_length=300, verbose_name="content")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="time")),
                (
                    "bugId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comment_set",
                        to="DataHandler.bugtuple",
                        verbose_name="Bug ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "bug评论",
                "verbose_name_plural": "bug评论(s)",
                "db_table": "comment",
                "ordering": ["-time"],
                "permissions": (("can_view_comment", "Can view comment"),),
                "get_latest_by": "time",
                "managed": True,
                "indexes": [
                    models.Index(fields=["time"], name="comment_time_1395b1_idx")
                ],
            },
        ),
    ]
