# Generated by Django 5.0.3 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CommentHandler", "0002_alter_comment_bugid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(verbose_name="time"),
        ),
    ]
