# Generated by Django 5.0.3 on 2024-04-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("DataHandler", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modified",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("user", models.CharField(max_length=50, verbose_name="user")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="time")),
                (
                    "bugId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bug_modified",
                        to="DataHandler.bugtuple",
                        verbose_name="Bug ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "bug修改",
                "verbose_name_plural": "bug修改(s)",
                "db_table": "modified",
                "ordering": ["-time"],
                "permissions": (("can_view_modified", "Can view modified"),),
                "get_latest_by": "time",
                "managed": True,
                "indexes": [
                    models.Index(fields=["time"], name="modified_time_388896_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Reported",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("user", models.CharField(max_length=50, verbose_name="user")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="time")),
                (
                    "bugId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bug_reported",
                        to="DataHandler.bugtuple",
                        verbose_name="Bug ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "bug报告",
                "verbose_name_plural": "bug报告(s)",
                "db_table": "reported",
                "ordering": ["-time"],
                "permissions": (("can_view_reported", "Can view reported"),),
                "get_latest_by": "time",
                "managed": True,
                "indexes": [
                    models.Index(fields=["time"], name="reported_time_1380f4_idx")
                ],
            },
        ),
    ]
