# Generated by Django 5.0.3 on 2024-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecordsHandler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modified",
            name="bugId",
            field=models.IntegerField(verbose_name="Bug ID"),
        ),
        migrations.AlterField(
            model_name="reported",
            name="bugId",
            field=models.IntegerField(verbose_name="Bug ID"),
        ),
    ]
