# Generated by Django 5.0.3 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecordsHandler", "0002_alter_modified_bugid_alter_reported_bugid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modified",
            name="time",
            field=models.DateTimeField(verbose_name="time"),
        ),
        migrations.AlterField(
            model_name="reported",
            name="time",
            field=models.DateTimeField(verbose_name="time"),
        ),
    ]
